BUG: remove unneeded apple framework headers
caused this on a new compiler/framework:
```
MacOSX10.11.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardware.h:162:2: error: expected identifier or '(' before '^' token
```
compiles fine without these headers